# Generated by Django 4.0.1 on 2022-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('mailid', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.TextField()),
            ],
        ),
    ]
