# Generated by Django 4.0.2 on 2022-04-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_about_banana_divine_heading_team_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('gallery', 'gallery'), ('product', 'product'), ('contact', 'contact')], max_length=20, unique=True)),
                ('heading_1', models.CharField(max_length=50)),
                ('heading_2', models.CharField(max_length=100)),
            ],
        ),
    ]
