# Generated by Django 4.0.1 on 2022-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_companydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
