# Generated by Django 4.0.2 on 2022-04-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_banners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='MainBanners',
        ),
    ]
