# Generated by Django 4.0.2 on 2022-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_banners_mainbanners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanners',
            name='category',
            field=models.CharField(choices=[('home', 'home'), ('about', 'about'), ('gallery', 'gallery'), ('contact', 'contact')], max_length=20, unique=True),
        ),
    ]
